---
title: "Source Documentation and Troubleshooting"
author:
  - name: Sajal Shrestha 
    url: https://sajalshres.github.io
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Coming from mindset of Python programming and having a limited knowledge of R, I faced a lot of challenges and issues when developing my projects and exploring R. Moreover, I also found identifying error message to be a time-consuming activity. I did a lot of search using Google, explored stackoverflow.com and used source documentation of libraries/packages. After a while, I got much better at detecting and fixing common errors by writing and practicing more R code.

For me, the most common error was Syntax errors. I would often miss to load the library, forget about closing a bracket or misspell the words. One best practice to quickly identify the error was to break the code into multiple lines.

For example, consider below code:

```
Orange %>% select(Tree, age, circumference) %>% group_by(Tree) %>% summarize(avg_circumference=mean(circumference))
```
The above code is much less readable as everything is in single-line. Breaking above code into multiple lines can significantly improve readability and at the same time identifying issues can be easier.

```
Orange %>%
  select(Tree, age, circumference) %>%
  group_by(Tree) %>%
  summarize(avg_circumference=mean(circumference))
```

