---
title: "Efficient and Well-documented R Programs"
author:
  - name: Sajal Shrestha 
    url: https://sajalshres.github.io
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

I have dedicated myself to spend good amount of time writing R code that included scripts, functions, packages, `rmarkdown` files and so on. I have developed my portfolio website using `distill` library that uses `rmarkdown` to generate html files. By making use of `rmarkdown` files, I've learned to include markdown contents, code chucks with inline code, tables, figures, output formats etc.

## Naming Conventions

I've learned about various naming conventions that can be used with R such as camelCase, snake_case, PascalCase etc. I've found that R doesn't have a stict naming conventions like Java, Python. But it is best to use conventions that yeilds meaningful and readable names. The `snake_case` works best for me as I find it more readable and easier for my issues. For funtion names, I prefer to use lower case with periods like test.case1.


## Project Structure

I have also learned to structure a R project. A good content organizations can help us to quickly navigate in a complex enterprise projects and can be scaled very easily. For my final project, I've used below structure:

```
sta-518-project
  |--- app
  |--- docs
  |--- scripts
  |--- data
  |.   |--- raw
  |.   |--- processed
  |--- .gitignore
  |--- README.md
```

## Functions and Packages

Functions and packages helps to breakdown complex piece of code into a single tasks that can be reused multiple times with out duplicating them. When developing ShinyApp for my project, I've created functions and scripts that can be used to complete various tasks for analysis. To accomplish this, I've used `source` function that helpe to resue function that is created in another R script.

## Documenting Code

I believe the most important aspect of documenting your code is to introduce comments. Comments helps to summarize the piece of code, provides notes to any important decision made or explain why something is implemented the way it is. It acts as a note for self in the future and make collaborating with other much easier. 

In addition, it is best to name the chuck of code when using R Markdown. The rstudio can make navigation much easier and we can generate table of content.

