---
title: "Essays"
author:
  - name: Sajal Shrestha 
    url: https://sajalshres.github.io
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Growth as a Data Person

**Note:** Work in progress. I intend to continually update it as I make my progress on course objectives and complete my final project. I will also include any problems I've encountered while making my progress and how I overcame it. 

Over the past few years, I have been fascinated by data science and wanted to advance my career as a Data Scientist. Before taking this class, I had limited experience with data science, analytics, and data in general. Most of my experience comes from being a system engineer, where I had some programming experience in Python and Shell scripting that I use to automate manual tasks. 

I am exhilarated to be part of the STA 518 course, as it will allow me to expand on my programming and statistical skills. Throughout the course, I've learned quite a bit about R programming and performing statistical analysis using the raw data. I've discovered how to process data from various sources and manipulate them to extract the essential features that can summarize important facts. I have learned to design functions that allows me to organize my project and make it more readable. Further, I can create visualizations that helps me convey a story through the data. For example, I can find which neighbourhoods in the city has the best prices for Airbnb listings using ggplot2 library. As I am making progress, I feel more confident that I can combine data and statistics to tell a story through graphics that can influence many readers.