---
title: "Essays"
author:
  - name: Sajal Shrestha 
    url: https://sajalshres.github.io
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Lightning Round

Answer each of the following questions with one sentence including a brief explanation.

### What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

The most difficult part for me is the fact that R programming is quite different from other languages like Python. I would consider myself a beginner to intermediate in Python programming. But coming to R, I feel like the syntax alienates me. I also find the naming conventions very confusing. Are we supposed to use **camelCase**, **snake_case**, **PascalCase** or **UPPER_SNAKE_CASE**?. For example, `read_csv` (or `read.csv`) and `readRDS` has different naming convention. I also find the error messages to be very unhelpful.

### What was the easiest part of the class for you? Explain why

The easiest part for me is working with Markdown and Github. This is due to the initial phases of our class focused on working on markdowns and collaborating on Github. The class activities and preparations have helped me a lot to grasp the concept. Even though sometimes I struggle with some concepts, I can work with my team and Dr.Bradford to sort out my confusion. I am quite pleased with the progress I am making with this course. 

### What part of the class surprised or interested you the most? Explain why.

I think the overall structure of the class is very cool. The online collaboration tools like Gather app and Teams is very effective. The class activities are interesting and excellently organized. We can connect Github and Rstudio in real-time and work on the activities.  Also as the class in not primarily focused around grades, It allows me to get out of my comfort zone and do more research and not worry about the risk of affecting my grades.

### Give one piece of advice to a student just beginning a semester of STA 418/518 that will help them be successful in learning.

I would suggest all the future students find their motivation in learning STA 418/518. I would encourage them to spend some time thinking about why they want to learn R and what would they do with it. It could be about building a project, working with a dataset they are interested in, or solving a problem. Figuring out what motivates you can help align course objectives and be successful in learning. I will also recommend completing all the weekly activities and preparation materials and asking questions in Microsoft teams or the classroom.
