# Reference: https://github.com/r-lib/actions/blob/v2/examples/shiny-deploy.yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: deploy-portfolio

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install Packages
        run: install.packages(c("distill", "tidyverse", "devtools", "GGally", "waffle", "devtools"))
        shell: Rscript {0}

      - name: Build site
        run: rmarkdown::render_site()
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh_pages
          folder: docs